class UserSelectionFonts {
  static const List<String> userFontsList = [
    'Roboto',
    'Lato',
    'Open Sans',
    'Montserrat',
    'Roboto Condensed',
    'Oswald',
    'Raleway',
    'Anton',
    'Noto Sans',
    'Ubuntu',
    'Open Sans Condensed',
    'Lora',
    'Nunito',
    'Rubik',
    'Nanum Gothic',
    'Titillium Web',
    'Inconsolata',
    'Fascinate',
    'Source Code Pro',
    'Josefin Sans',
    'Lobster',
    'Dancing Script',
    'Yanone Kaffeesatz',
    'Fjalla One',
    'Bebas Neue',
    'Cairo',
    'Indie Flower',
    'Pacifico',
    'Architects Daughter',
    'Shadows Into Light',
    'Overpass',
    'Ravi Prakash',
    'Cormorant Garamond',
    'Fredoka One',
    'Caveat',
    'Permanent Marker',
    'Patrick Hand',
    'Righteous',
    'Vollkorn',
    'Courgette',
    'Kavivanar',
    'Kaushan Script',
    'Lobster Two',
    'Great Vibes',
    'Kalam',
    'Sacramento',
    'Parisienne',
    'Gloria Hallelujah',
    'Orbitron',
    'Passion One',
    'Josefin Slab',
    'Monda',
    'Volkhov',
    'Merienda',
    'Hammersmith One',
    'Istok Web',
  ];
}
